default:
  tags:
    - docker
    - ubuntu

  image: "neus.nic.etu:8081/nic/fedora_33:base"

stages:
  - test

unit_tests:
  stage: test
  script:
    - dnf update -y && dnf install -y python3 python3-pip python3-qt5 qt5-qtbase-devel
    - pip3 install -r requirements.txt
    - export PYTHONPATH=$(pwd)/server
    - pytest server/tests
