stages:
  - build
  - test

build:
  stage: build
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Building project..."

test:
  stage: test
  script:
    - echo "Running tests..."
    - pytest --maxfail=1 --disable-warnings -q || { echo 'Tests failed'; exit 1; }
